# Deep Learning Basics - Foundation Concepts for LLM Development

## Lab Overview

This lab covers the fundamental concepts of deep learning that are essential for understanding Large Language Models and transformer architectures. We'll explore tensors, operations, gradients, and the mathematical foundations of neural networks.

## Learning Objectives

By the end of this lab, you will:
- Master PyTorch tensor operations and computational graphs
- Understand automatic differentiation and gradient computation
- Learn the mathematical foundations of neural network training
- Explore forward and backward propagation mechanics
- Set up AMD GPU backend for accelerated deep learning
- Connect basic operations to transformer architectures

---

In [ ]:


# GPU Setup and Essential Imports
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt

# Configure device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")
print(f"PyTorch version: {torch.__version__}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

AMD GPU environment initialized successfully
Using device: cuda
PyTorch version: 2.6.0+gitdbfe118
GPU: AMD Radeon Graphics
GPU Memory: 68.7 GB


## 1. Tensor Fundamentals

Tensors are the fundamental data structure in PyTorch and the building blocks of deep learning. Understanding tensors is crucial for working with neural networks and LLMs.

In [2]:
# 1.1 Creating Tensors and Basic Operations

print("=== Tensor Creation and Properties ===")

# Create tensors on GPU for optimal performance
x = torch.randn(10, 5, device=device)  # Input tensor: 10 samples, 5 features each
w = torch.randn(5, 3, requires_grad=True, device=device)  # Weight matrix: 5 inputs → 3 outputs

print(f"Input tensor shape: {x.shape} | Device: {x.device}")
print(f"Weight tensor shape: {w.shape} | Device: {w.device}")
print(f"Weight requires gradients: {w.requires_grad}")

print(f"\nInput tensor (first 3 samples):\n{x[:3]}")
print(f"\nWeight tensor:\n{w}")

print(f"\nKey Insight: This setup simulates a neural network layer:")
print(f"   • Input: 10 samples with 5 features each")
print(f"   • Weights: Transform 5 input features to 3 output features")
print(f"   • This is the foundation of deep learning transformations!")

=== Tensor Creation and Properties ===
Input tensor shape: torch.Size([10, 5]) | Device: cuda:0
Weight tensor shape: torch.Size([5, 3]) | Device: cuda:0
Weight requires gradients: True

Input tensor (first 3 samples):
tensor([[ 1.3724,  1.7079, -0.7715,  1.0109, -0.9245],
        [-0.5732, -0.5275, -0.8735, -0.4287, -0.5490],
        [ 0.9194, -0.2916,  1.2114,  0.1493,  1.8290]], device='cuda:0')

Weight tensor:
tensor([[-0.2294, -0.0981, -1.4152],
        [ 2.4635,  1.3061,  1.3296],
        [-1.0522, -0.5378,  0.4154],
        [-0.9954,  0.8733,  0.0390],
        [ 1.5269,  0.3540, -0.8602]], device='cuda:0', requires_grad=True)

Key Insight: This setup simulates a neural network layer:
   • Input: 10 samples with 5 features each
   • Weights: Transform 5 input features to 3 output features
   • This is the foundation of deep learning transformations!


In [3]:
# 1.2 Matrix Multiplication - The Heart of Neural Networks

print("=== Matrix Multiplication Methods ===")

# Method 1: @ operator (most commonly used)
y1 = x @ w  # Shape: (10, 5) @ (5, 3) → (10, 3)
print(f"Method 1 (@): {x.shape} @ {w.shape} → {y1.shape}")
print(f"Result (first 3 samples):\n{y1[:3]}")

# Method 2: .matmul() method
y2 = x.matmul(w)
print(f"\nMethod 2 (.matmul()): {y2.shape}")
print(f"Results identical: {torch.allclose(y1, y2)}")

# Method 3: torch.matmul() function
y3 = torch.matmul(x, w)
print(f"\nMethod 3 (torch.matmul()): {y3.shape}")
print(f"All methods identical: {torch.allclose(y1, y3)}")

print(f"\nUnderstanding the Transformation:")
print(f"   • Each of 10 samples (rows) gets transformed")
print(f"   • From 5 input features to 3 output features")
print(f"   • This is exactly what happens in neural network layers!")
print(f"   • Essential for: Linear layers, Attention mechanisms, LLM computations")

=== Matrix Multiplication Methods ===
Method 1 (@): torch.Size([10, 5]) @ torch.Size([5, 3]) → torch.Size([10, 3])
Result (first 3 samples):
tensor([[ 2.2865,  3.0665,  0.8429],
        [-0.6604, -0.7316,  0.2025],
        [ 0.4402, -0.3449, -2.7532]], device='cuda:0',
       grad_fn=<SliceBackward0>)

Method 2 (.matmul()): torch.Size([10, 3])
Results identical: True

Method 3 (torch.matmul()): torch.Size([10, 3])
All methods identical: True

Understanding the Transformation:
   • Each of 10 samples (rows) gets transformed
   • From 5 input features to 3 output features
   • This is exactly what happens in neural network layers!
   • Essential for: Linear layers, Attention mechanisms, LLM computations


In [ ]:
# 1.3 PyTorch Linear Layers - Neural Network Building Blocks

# Recall these parameters:
# x: input tensor of shape (10, 5)
# w: weight tensor of shape (5, 3)
# y_manual_matmul: the result from the manual x @ w calculation
# device: the target device ('cuda')
TODO = None
# Now fill in the code below with marked 'TODO'

print("=== PyTorch Linear Layer Exercise ===")

# --- 1. Create the linear layer ---
# Define a linear layer with 5 input features and 3 output features.
# Make sure to disable the bias and move the layer to the correct device.
# YOUR CODE HERE
linear = torch.nn.Linear(in_features=TODO, out_features=TODO, bias=False).to(device)

print(f"Linear layer created. Weight shape: {linear.weight.shape}")
print(f"Layer is on device: {linear.weight.device}")
print(f"Layer bias is: {linear.bias}")  # Should be TODO

# --- 2. Set the weights manually ---
# The layer's `weight` attribute has a shape of (out_features, in_features).
# Our `w` tensor has a shape of (in_features, out_features).
# You will need to transpose `w` before assigning it.
# YOUR CODE HERE
linear.weight.data = TODO

print(f"\nOriginal weight matrix w (shape {w.shape}):\n{w}")
print(
    f"Linear layer weight after setting (shape {linear.weight.shape}):\n{linear.weight}"
)

# --- 3. Apply the linear transformation ---
# Pass the input tensor `x` through the layer to compute the output.
# Use the layer as a function: `y_linear = linear(x)`
# YOUR CODE HERE
y_linear = TODO

print(f"\nLinear layer output shape: {y_linear.shape}")
print(f"First 3 outputs:\n{y_linear[:3]}")


# Here we calculate the result manually
# Get dimensions
x_rows, x_cols = len(x), len(x[0])
w_rows, w_cols = len(w), len(w[0])

# Ensure the matrices can be multiplied
if x_cols != w_rows:
    raise ValueError(
        "The number of columns in matrix 'x' must equal the number of rows in matrix 'w'."
    )

# Initialize the result matrix with zeros
# The shape will be (x_rows, w_cols) -> (10, 3)
y_manual_matmul = [[0 for _ in range(w_cols)] for _ in range(x_rows)]

# Perform the multiplication
for i in range(x_rows):
    for j in range(w_cols):
        for k in range(x_cols):  # or w_rows
            y_manual_matmul[i][j] += x[i][k] * w[k][j]

# Print the Manual Result
print("Result of y_manual_matmul (calculated without Torch):")
for row in y_manual_matmul:
    # Print each row with formatting for clarity
    print([f"{val:.2f}" for val in row])

# --- 4. Verify equivalence ---
# Use torch.allclose() to confirm the results are the same.
# This should return True if your implementation is correct.
are_equivalent = torch.allclose(y_manual_matmul, y_linear)
print(f"\nManual matmul vs Linear layer outputs are equivalent: {are_equivalent}")

# Assert that the check passes
assert are_equivalent, "Outputs do not match! Please review your code."

print("\nGreat job! You've successfully used a PyTorch Linear layer.")

=== PyTorch Linear Layer ===
Linear layer weight shape: torch.Size([3, 5])
Linear layer on device: cuda:0
Linear layer bias: None

Original weight matrix w:
tensor([[-0.2294, -0.0981, -1.4152],
        [ 2.4635,  1.3061,  1.3296],
        [-1.0522, -0.5378,  0.4154],
        [-0.9954,  0.8733,  0.0390],
        [ 1.5269,  0.3540, -0.8602]], device='cuda:0', requires_grad=True)
Linear layer weight (w^T):
Parameter containing:
tensor([[-0.2294,  2.4635, -1.0522, -0.9954,  1.5269],
        [-0.0981,  1.3061, -0.5378,  0.8733,  0.3540],
        [-1.4152,  1.3296,  0.4154,  0.0390, -0.8602]], device='cuda:0',
       requires_grad=True)

Linear layer output shape: torch.Size([10, 3])
First 3 outputs:
tensor([[ 2.2865,  3.0665,  0.8429],
        [-0.6604, -0.7316,  0.2025],
        [ 0.4402, -0.3449, -2.7532]], device='cuda:0',
       grad_fn=<SliceBackward0>)

Manual matmul vs Linear layer: True

PyTorch Linear Layers are:
   • The building blocks of neural networks
   • Used in: MLPs, Trans

## 2. Automatic Differentiation - The Magic of Backpropagation

Automatic differentiation (autograd) is PyTorch's system for computing gradients automatically. This is essential for training neural networks through backpropagation.

### 2.1 Gradient Computation Example

In [ ]:

print("=== Automatic Differentiation in Action ===")

batch_size = 10
in_features = 20
hidden_features = 8
out_features = 3

input_data = torch.randn(batch_size, in_features, device=device)
target = torch.randn(batch_size, out_features, device=device)
reg_strength = 0.01 # This is our lambda (λ) for regularization

# --- 1. Initialize Network Parameters ---
# Create the weight and bias tensors for both layers.
# They must have requires_grad=True to track gradients.
# Layer 1 parameters
w1 = torch.randn(in_features, hidden_features, requires_grad=True, device=device)
b1 = torch.randn(hidden_features, requires_grad=True, device=device)

# Layer 2 parameters
# w2 means the weights for the second layer, and b2 means the biases for the second layer.
# Remember the shape: w2 should transform from hidden_features to out_features.#
w2 = TODO
b2 = TODO

# --- 2. Implement the Forward Pass ---
# Follow the architecture: Linear -> ReLU -> Linear
# First layer transformation
# Math for first layer: hidden_input = input_data @ w1 + b1
hidden_input = TODO
# ReLU activation
# ReLU sets all negative values to zero, keeping positive values unchanged.
# Math for ReLU: hidden_output = max(0, hidden_input)
# You can use F.relu() for this.
hidden_output = TODO
# Second layer transformation
# Math for second layer: prediction = hidden_output @ w2 + b2
prediction = TODO

# --- 3. Calculate Composite Loss ---
# a. Calculate the Mean Squared Error (MSE) between prediction and target.
# MSE is calculated as the average of the squared differences between predicted and target values.
# Math for MSE: mse_loss = (1/N) * sum((prediction - target)^2) where N is the number of samples.
mse_loss = TODO

# b. Calculate the L2 regularization penalty.
# It's the sum of squares of all elements in w1 and w2.
# Math for L2: l2_reg = reg_strength  * (sum(w1^2) + sum(w2^2))
l2_reg = TODO

# c. Combine them for the final loss.
# Total loss = MSE loss + L2 regularization penalty
total_loss = TODO

print(f"Forward Pass Completed:")
print(f"  Prediction shape: {prediction.shape}")
print(f"  Total Loss: {total_loss.item():.4f}")


# --- 4. Perform Backward Pass ---
# This part is done for you. PyTorch computes the gradients from the final loss.
total_loss.backward()

print(f"\nBackward Pass Completed. Gradients are now available.")
print(f"  Gradient for w1 has shape: {w1.grad.shape}")
print(f"  Gradient for b1 has shape: {b1.grad.shape}")
print(f"  Gradient for w2 has shape: {w2.grad.shape}")
print(f"  Gradient for b2 has shape: {b2.grad.shape}")
print(f"  Norm of w1 gradient: {w1.grad.norm().item():.4f}")
# Determine corectness by checking if gradients are non-zero
assert w1.grad.norm().item() > 0, "Gradient for w1 is zero! Check your loss calculation and backward pass."
assert w2.grad.norm().item() > 0, "Gradient for w2 is zero! Check your loss calculation and backward pass."

=== Automatic Differentiation in Action ===
Input shape: torch.Size([4, 5])
Target shape: torch.Size([4, 3])
Weight shape: torch.Size([5, 3])
Bias shape: torch.Size([3])

Forward pass:
  Prediction shape: torch.Size([4, 3])
  Loss value: 11.5263

Gradients computed:
  Weight gradient shape: torch.Size([5, 3])
  Bias gradient shape: torch.Size([3])
  Weight gradient norm: 5.0719
  Bias gradient norm: 1.3227

This is how neural networks learn:
   1. Forward pass: Compute predictions
   2. Loss computation: Measure prediction error
   3. Backward pass: Compute gradients (∂Loss/∂parameters)
   4. Parameter update: Adjust weights to reduce loss


### 2.2 Element-wise multiplication 

Element-wise multiplication applies the same operation independently to every position of two tensors with the **same shape** (or shapes that are **broadcastable**). In PyTorch you can use `*`, `.mul()`, or `torch.mul()`—they’re equivalent for element-wise multiply.

**Definition (Hadamard product):** for tensors `A, B ∈ R^{m×n}`,
`(A ⊙ B)_{ij} = A_{ij} × B_{ij}`.

**Why it matters**
- Used in gating (e.g., LSTM/GRU gates), attention masks, feature-wise scaling (LayerNorm/FiLM), and residual modulation.
- Preserves shape, dtype, and device of the inputs; gradients flow element-by-element via autograd.
- Squaring a tensor is just element-wise multiplication with itself: `z = w * w` (same as `w.pow(2)`). The gradient is `∂z/∂w = 2w`.

**Element-wise vs. matrix multiply**
- `*` multiplies element-by-element and returns the same shape as the inputs (after broadcasting).
- `@` / `matmul` performs linear-algebraic matrix multiplication, e.g., `(m×k) @ (k×n) → (m×n)`.

Below, we print `w`, compute `z = w * w`, and verify that a single entry squared (`w[i][j]**2`) equals the corresponding entry `z[i][j]`.

In [6]:
# element wise multiplication

print(w)

z = w * w

print(z)

i = 3
j = 2
print(w[i][j]**2)

tensor([[-0.2294, -0.0981, -1.4152],
        [ 2.4635,  1.3061,  1.3296],
        [-1.0522, -0.5378,  0.4154],
        [-0.9954,  0.8733,  0.0390],
        [ 1.5269,  0.3540, -0.8602]], device='cuda:0', requires_grad=True)
tensor([[5.2609e-02, 9.6317e-03, 2.0027e+00],
        [6.0690e+00, 1.7058e+00, 1.7679e+00],
        [1.1071e+00, 2.8926e-01, 1.7258e-01],
        [9.9077e-01, 7.6261e-01, 1.5172e-03],
        [2.3316e+00, 1.2529e-01, 7.3992e-01]], device='cuda:0',
       grad_fn=<MulBackward0>)
tensor(0.0015, device='cuda:0', grad_fn=<PowBackward0>)


## Tensor dtypes & devices (precision casting)

Modern deep learning performance depends heavily on **dtype** (numeric precision) and **device** (CPU/GPU). PyTorch tensors carry both:
- `dtype` (e.g., `torch.float32`, `torch.bfloat16`, `torch.float16`, `torch.int64`)
- `device` (e.g., `cpu`, `cuda:0`, `mps:0`)

**Why change dtype?**
- **bfloat16 (bf16)** keeps the same exponent range as fp32 with fewer mantissa bits → great for **stable mixed-precision training** on modern GPUs (including AMD ROCm) while saving memory and boosting throughput.
- **float16 (fp16)** is faster but has a smaller exponent range → may under/overflow more easily than bf16.
- **float32 (fp32)** is the safe default for numerical stability, but uses more memory/compute.

Below, we print a tensor’s `dtype` and `device`, cast it to `bfloat16`, and confirm the new dtype.

In [7]:
print(w, w.dtype, w.device)
w1 = w.bfloat16()
print(w1.dtype)

tensor([[-0.2294, -0.0981, -1.4152],
        [ 2.4635,  1.3061,  1.3296],
        [-1.0522, -0.5378,  0.4154],
        [-0.9954,  0.8733,  0.0390],
        [ 1.5269,  0.3540, -0.8602]], device='cuda:0', requires_grad=True) torch.float32 cuda:0
torch.bfloat16


## 3. Neural Network Architectures

Now let's explore how these fundamental operations combine to create neural networks, from simple multi-layer perceptrons to convolutional networks.

In [8]:
m1 = nn.Linear(20, 30)
m2 = nn.Linear(30, 40)
x = torch.randn(128, 20)
y1 = m1(x)
y2 = m2(y1)
print(y2.shape)

torch.Size([128, 40])


In [9]:
x_large = torch.randn(128, 4096,30, 20)
y1_large = m1(x_large)
y2_large = m2(y1_large)
print(y2.shape)

torch.Size([128, 40])


In [10]:
x = torch.ones((1,1,5,5))
print(x)
x[:,:,:,0]=0
x[:,:,:,1]=0
x[:,:,0,:]=0
x[:,:,1,:]=0
print(x)
conv_w = torch.ones((1,1,3,3))

y = nn.functional.conv2d(x, conv_w)
print(y)

tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])
tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 1., 1., 1.],
          [0., 0., 1., 1., 1.],
          [0., 0., 1., 1., 1.]]]])
tensor([[[[1., 2., 3.],
          [2., 4., 6.],
          [3., 6., 9.]]]])


## 4. Complete Training Pipeline

Now let's put everything together into a complete deep learning training pipeline using a classic CNN architecture on a real dataset.

In [11]:
# 4.1 Dataset Loading and Preparation

print("=== Loading FashionMNIST Dataset ===")

from torch.utils.data import Dataset, DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

# Load FashionMNIST dataset
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor()
)

# Create data loaders for batched training
batch_size = 64
train_dataloader = DataLoader(training_data, batch_size=batch_size, shuffle=True)
test_dataloader = DataLoader(test_data, batch_size=batch_size, shuffle=False)

print(f"Dataset Information:")
print(f"  Training samples: {len(training_data):,}")
print(f"  Test samples: {len(test_data):,}")
print(f"  Batch size: {batch_size}")
print(f"  Training batches: {len(train_dataloader):,}")
print(f"  Test batches: {len(test_dataloader):,}")

# Check data format
sample_batch = next(iter(train_dataloader))
images, labels = sample_batch
print(f"\nBatch Information:")
print(f"  Image batch shape: {images.shape}")  # [batch_size, channels, height, width]
print(f"  Label batch shape: {labels.shape}")  # [batch_size]
print(f"  Image range: [{images.min():.3f}, {images.max():.3f}]")
print(f"  Unique labels in batch: {torch.unique(labels).tolist()}")

# Fashion-MNIST class names
class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']
print(f"\nClass names: {class_names}")

=== Loading FashionMNIST Dataset ===
Dataset Information:
  Training samples: 60,000
  Test samples: 10,000
  Batch size: 64
  Training batches: 938
  Test batches: 157

Batch Information:
  Image batch shape: torch.Size([64, 1, 28, 28])
  Label batch shape: torch.Size([64])
  Image range: [0.000, 1.000]
  Unique labels in batch: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Class names: ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']


In [ ]:
# 4.2 LeNet Architecture - Classic Convolutional Neural Network

print("=== LeNet-5 Architecture ===")

class LeNet(nn.Module):
    def __init__(self, num_classes=10):
        super().__init__()
        # Convolutional layers
        self.conv1 = nn.Conv2d(1, 6, kernel_size=5)    # 28x28 → 24x24
        self.conv2 = nn.Conv2d(6, 16, kernel_size=5)   # 12x12 → 8x8

        # Fully connected layers
        self.fc1 = nn.Linear(16*4*4, 120)  # 16 channels × 4×4 = 256 → 120
        self.fc2 = nn.Linear(120, 84)      # 120 → 84
        self.fc3 = nn.Linear(84, num_classes)  # 84 → 10 classes

    def forward(self, x):
        # Conv layer 1 + ReLU + MaxPool
        x = F.relu(self.conv1(x))        # [batch, 6, 24, 24]
        x = F.max_pool2d(x, 2, 2)       # [batch, 6, 12, 12]

        # Conv layer 2 + ReLU + MaxPool
        x = F.relu(self.conv2(x))        # [batch, 16, 8, 8]
        x = F.max_pool2d(x, 2, 2)       # [batch, 16, 4, 4]

        # Flatten for fully connected layers
        x = x.view(-1, 16*4*4)           # [batch, 256]

        # Fully connected layers
        x = F.relu(self.fc1(x))          # [batch, 120]
        x = F.relu(self.fc2(x))          # [batch, 84]
        x = self.fc3(x)                  # [batch, 10]
        return x

# Now try to implement a modernized LeNet-style CNN

class ModernLeNet(nn.Module):
    """
    A modernized LeNet-style CNN with BatchNorm and Dropout,
    built using nn.Sequential containers.
    """
    def __init__(self, in_channels=1, num_classes=10):
        super().__init__()
        TODO=None
        # --- 1. Define the Feature Extraction Block ---
        # This block will handle the convolutions and pooling.
        # Architecture:
        #   - Conv2d: in_channels -> 6 channels, kernel size 5
        #   - BatchNorm2d: for the 6 channels
        #   - ReLU activation
        #   - MaxPool2d: kernel size 2, stride 2
        #   - Conv2d: 6 channels -> 16 channels, kernel size 5
        #   - BatchNorm2d: for the 16 channels
        #   - ReLU activation
        #   - MaxPool2d: kernel size 2, stride 2
        self.features = nn.Sequential(
            nn.Conv2d(in_channels, 6, kernel_size=5), # Conv1
            nn.BatchNorm2d(6), # BatchNorm1
            nn.ReLU(), # ReLU1
            nn.MaxPool2d(kernel_size=2, stride=2), # MaxPool1
            nn.Conv2d(TODO, TODO, kernel_size=TODO), # Conv2
            nn.BatchNorm2d(TODO), # BatchNorm2
            TODO = None, # ReLU2
            nn.MaxPool2d(kernel_size=TODO, stride=TODO)  # MaxPool2
        )

        # --- 2. Calculate the input size for the classifier ---
        # This is a robust way to connect conv and linear layers.
        # We pass a dummy tensor through the `features` block to see the output shape.
        self._conv_output_size = self._get_conv_output_size(in_channels)

        # --- 3. Define the Classifier Block ---
        # This block will handle the final classification.
        # Architecture:
        #   - Linear: from flattened feature size -> 120
        #   - ReLU activation
        #   - Dropout: with a probability of 0.5
        #   - Linear: 120 -> 84
        #   - ReLU activation
        #   - Linear: 84 -> num_classes
        self.classifier = nn.Sequential(
            nn.Linear(self._conv_output_size, TODO), # FC1
            TODO = None, # ReLU1
            nn.Dropout(TODO), # Dropout
            nn.Linear(TODO, TODO), # FC2
            TODO = None, # ReLU2
            nn.Linear(TODO, TODO)  # FC3 (output)
        )

    def _get_conv_output_size(self, in_channels):
        # Create a dummy input tensor with the correct shape (batch_size=1, channels, height, width)
        # We assume a standard 28x28 input image like MNIST.
        dummy_input = torch.randn(1, in_channels, 28, 28)
        # Pass it through the feature extractor
        output = self.features(dummy_input)
        # Calculate the total number of features after flattening
        # The output shape will be [1, channels, height, width], so we multiply these together.
        # Math for flattened size: channels * height * width
        # We use torch.flatten to get the total number of features after the conv layers.
        # The output of torch.flatten(output, 1) will have shape [1, flattened_size], so we can get flattened_size from that.
        # For example, if output shape is [1, 16, 4, 4], then flattened size = 16 * 4 * 4 = 256.
        # flattened_size = int(torch.flatten(output, 1).size(1))
        flattened_size = TODO = None
        print(f"Dynamically calculated flattened size for FC layer: {flattened_size}")
        return flattened_size

    def forward(self, x):
        # --- 4. Implement the full forward pass ---
        # a. Pass input through the feature extractor
        # The output will be a 4D tensor with shape [batch_size, channels, height, width].
        # We will need to flatten this before passing it to the classifier.
        # Math for feature extraction: features_out = self.features(x)
        features_out = TODO = None
        # b. Flatten the output from the feature extractor.
        # Use torch.flatten starting from the first dimension (dim=1)
        # to keep the batch dimension.
        # Math for flattening: flattened = torch.flatten(features_out, 1)
        flattened = TODO = None
        # c. Pass the flattened tensor through the classifier
        # Math for classification: final_output = self.classifier(flattened)
        final_output = TODO = None
        return final_output

def analyze_model(model, model_name, device):
    """
    Prints architecture, statistics, and tests the forward pass for a given model.
    """
    print(f"=============== Analysis for: {model_name} ===============")
    model.to(device)

    # Print Architecture
    print("Model Architecture:")
    print(model)

    # Count Parameters
    total_params = sum(p.numel() for p in model.parameters())
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

    print("\nModel Statistics:")
    print(f"  Total Parameters: {total_params:,}")
    print(f"  Trainable Parameters: {trainable_params:,}")

    # Test Forward Pass
    try:
        test_input = torch.randn(4, 1, 28, 28, device=device) # Batch size of 4
        test_output = model(test_input)
        print("\nTest Forward Pass:")
        print(f"  Input shape:  {test_input.shape}")
        print(f"  Output shape: {test_output.shape}")
        assert test_output.shape == (4, 10)
        print("  Forward pass successful!")
    except Exception as e:
        print(f"\nForward pass failed: {e}")

    print("=" * (50 + len(model_name)) + "\n")


# --- Execution ---
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}\n")

# 1. Instantiate and analyze the original LeNet model
lenet_classic = LeNet(num_classes=10)
analyze_model(lenet_classic, "Classic LeNet-5", device)

# 2. Instantiate and analyze the modern LeNet model
lenet_modern = ModernLeNet(in_channels=1, num_classes=10)
analyze_model(lenet_modern, "ModernLeNet with BatchNorm & Dropout", device)

=== LeNet-5 Architecture ===
Model Architecture:
LeNet(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=256, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

Model Statistics:
  Total parameters: 44,426
  Trainable parameters: 44,426
  Model device: cuda:0

Test forward pass:
  Input shape: torch.Size([1, 1, 28, 28])
  Output shape: torch.Size([1, 10])
  Output probabilities: tensor([0.0951, 0.1050, 0.1063, 0.1074, 0.0990], device='cuda:0',
       grad_fn=<SliceBackward0>)


In [ ]:
# 4.3 Complete Training Pipeline

print("=== Training Setup ===")
# Try to train defferent LeNet architectures by switching the comment on the line below.
model = LeNet(num_classes=10).to(device)
#model = ModernLeNet(num_classes=10).to(device)
print(f"Model instantiated: {model.__class__.__name__}")

# --- 1. Define Loss Function and Optimizer ---
# We'll use Cross-Entropy Loss for this multi-class classification problem.
criterion = nn.CrossEntropyLoss()
# For the optimizer, try using Adam, a popular and effective alternative to SGD.
# Look up the documentation for torch.optim.Adam.
# torch.optim.Adam takes the model parameters and a learning rate as arguments.
# You can call by passing (model.parameters(), lr ) to the optimizer to tell it which parameters to update.
#  A learning rate of 1e-3 is a good start.
optimizer = torch.optim.Adam(TODO, lr=TODO)

print(f"Loss function: {criterion}")
print(f"Optimizer: {optimizer}")

def train_epoch(dataloader, model, loss_fn, optimizer, device):
    """Trains the model for one epoch."""
    model.train() # Set the model to training mode
    total_loss = 0
    correct_predictions = 0
    total_samples = 0

    for batch_idx, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)

        # --- 2. Forward Pass ---
        # Get the model's predictions (logits) for the input batch.
        # Then, calculate the loss between the predictions and the true labels.
        predictions = model(X)
        # The loss function will compare the predicted logits with the true labels `y`.
        # For CrossEntropyLoss, `predictions` should be raw logits (not probabilities), and `y` should be the class indices.
        # Math for loss: loss = loss_fn(predictions, y)
        loss = loss_fn(TODO, TODO)

        # --- 3. Backward Pass & Optimizer Step ---
        # First, clear the gradients from the previous step.
        # Then, perform backpropagation to compute gradients.
        # Finally, update the model's weights using the optimizer.
        optimizer.zero_grad() # Zero gradients
        loss.backward()  # Backpropagate
        optimizer.step()  # Update weights

        # --- 4. Track Statistics ---
        # We track loss and accuracy to monitor training progress.
        total_loss += loss.item()
        # Find the index of the max logit for each sample to get the predicted class.
        # Math for predicted class: _, predicted_classes = torch.max(predictions, dim=1)
        _, predicted_classes = torch.max(TODO, TODO)
        total_samples += y.size(0)
        correct_predictions += (predicted_classes == y).sum().item()

    avg_loss = total_loss / len(dataloader)
    accuracy = 100. * correct_predictions / total_samples
    return avg_loss, accuracy

def test_epoch(dataloader, model, loss_fn, device):
    """Evaluates the model on the test dataset."""
    model.eval() # Set the model to evaluation mode
    total_loss = 0
    correct_predictions = 0
    total_samples = 0

    # In evaluation, we don't need to compute gradients.
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)

            # --- 5. Evaluation Forward Pass ---
            # This is similar to training, but without the backward pass.
            # Get predictions and calculate the loss.
            predictions = TODO = None
            # Calculate the loss for this batch using the same loss function as training.
            loss = TODO = None

            # --- 6. Track Evaluation Statistics ---
            total_loss += loss.item()
            _, predicted_classes = TODO = None
            total_samples += y.size(0)
            correct_predictions += (predicted_classes == y).sum().item()

    avg_loss = total_loss / len(dataloader)
    accuracy = 100. * correct_predictions / total_samples
    return avg_loss, accuracy

# --- The Main Training Loop (Provided for you) ---
print(f"\n=== Starting Training on {device} ===")
epochs = 5
train_losses, train_accs = [], []
test_losses, test_accs = [], []

for epoch in range(epochs):
    print(f"\n--- Epoch {epoch+1}/{epochs} ---")

    train_loss, train_acc = train_epoch(train_dataloader, model, criterion, optimizer, device)
    train_losses.append(train_loss)
    train_accs.append(train_acc)

    test_loss, test_acc = test_epoch(test_dataloader, model, criterion, device)
    test_losses.append(test_loss)
    test_accs.append(test_acc)

    print(f"Train Loss: {train_loss:.4f} | Train Acc: {train_acc:.2f}%")
    print(f"Test  Loss: {test_loss:.4f} | Test  Acc: {test_acc:.2f}%")

print(f"\n=== Training Complete! ===")
print(f"Final Test Accuracy: {test_accs[-1]:.2f}%")

print(f"\nKey Learning Points:")
print(f"   • Forward pass: Data flows through network layers")
print(f"   • Loss computation: Measures prediction errors")
print(f"   • Backward pass: Computes gradients via chain rule")
print(f"   • Parameter update: Moves in direction of negative gradient")
print(f"   • This is the foundation of ALL deep learning!")
print(f"   • Same principles apply to LLMs, just different architectures")

=== Training Setup ===
Loss function: CrossEntropyLoss()
Optimizer: SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.001
    maximize: False
    momentum: 0.9
    nesterov: False
    weight_decay: 0
)

=== Training Started ===

Epoch 1/5
--------------------------------------------------
  Batch   0/938 | Loss: 2.3007 | Acc:  15.6%
  Batch 200/938 | Loss: 2.3005 | Acc:  11.1%
  Batch 400/938 | Loss: 2.2898 | Acc:  14.9%
  Batch 600/938 | Loss: 2.2421 | Acc:  17.2%
  Batch 800/938 | Loss: 1.6519 | Acc:  20.6%

Epoch 1 Summary:
  Train Loss: 2.1081 | Train Acc: 25.17%
  Test Loss:  1.1206 | Test Acc:  55.44%

Epoch 2/5
--------------------------------------------------
  Batch   0/938 | Loss: 1.0757 | Acc:  57.8%
  Batch 200/938 | Loss: 0.9096 | Acc:  60.0%
  Batch 400/938 | Loss: 0.9315 | Acc:  62.3%
  Batch 600/938 | Loss: 0.9016 | Acc:  64.2%
  Batch 800/938 | Loss: 0.8477 | Acc:  65.5%

Epoch 2 Summary:
  Train Loss: 0.876